### ISSUE TITLE
Its not working on Feather Launcher

### ISSUE THREAD

**Issue by Denower234** [ItziSpyder/ClickCrystals#21]
When i right shift it opens the feather menu. But i cant change the keybind

**Comment by ItziSpyder** [comment]
If you are on 1.20.x, download latest version 0.9.9 and execute command `,keybinds`. This should open up keybinds menu.

**Comment by ItziSpyder** [comment]
If you are on 1.19.x, change keybinds via Minecraft options.

**Comment by Denower234** [comment]
ok i will try, thank you for the fast answer

**Comment by ItziSpyder** [comment]
> Sorry, I couldn't explain. I can open the keybinds menu but there is nothing to change the keybind of clickcrystals. I know that it is opened with right shift but the button is replaced with feather settings menu

Like I said, there are a few ways to face this problem. Trust me, I get these messages on the daily.

If you are on `1.19.x`:
_Go to Game Menu, selection Options, go to Keybinds, then scroll down to change the ClickCrystals Open Modules Screen keybind_

If you are on `1.20.x`
_Download the latest ClickCrystals version `0.9.9`, then execute the command `,keybinds` and change the custom keybinds there_

The reason for these differences is because the ClickCrystals community has decided to make an entirely new keybinds system during the 1.20 update due to excessive amounts of __screensharing__. During this update, __1.19.x has been discontinued__ therefore not receiving this keybinds revamp.

So instead of whining about not being able to change the keybinds of ClickCrystals and __completely disregarding my previous message__:

> If you are on 1.20.x, download the latest version 0.9.9 and execute the command ,keybinds. This should open up keybinds menu. If you are on 1.19.x, change keybinds via Minecraft options.

Please consider trying the options that I have listed.

**Comment by ItziSpyder** [comment]
bro i swear i'll make this response a copy pasta if i have to 😭

**Comment by ItziSpyder** [comment]
This issue is now resolved closed

**Comment by Denower234** [comment]
i updated bruh

**Comment by ItziSpyder** [comment]
Join my discord server let me staff team help you I lost enough brain cells already
