### ISSUE TITLE
Can I Use It For 1.16.5

### ISSUE THREAD

**Issue by Spyplayz13** [ItziSpyder/ClickCrystals#24]
If Not Please Suggest Me Other Optimzer That Can Be Used In 1.16.5

**Comment by ItziSpyder** [comment]
ClickCrystals is not an optimizer, it is an attempt to remove an annoying and unnecessary concept of the game: hotkeying. And please update your game, as 16.5 was well over 2 years ago.

**Comment by Ragua7065** [comment]
I agree with u but guys like me who use 1.16.5 who got 1st gen pc which cant run even 1.17 , how will they play 1.20 . And We cant buy new one because we are minors . So its my humble request to downgrade it to 1.16.5 only once. We will not request u for more updates . If u are unable , u may tell me the steps so that I may do that (if it would be easy ) . But I request just try to think about it pls.

**Comment by ItzNoOne** [comment]
Just use performance modpack and u got to go

**Comment by Ragua7065** [comment]
Firstly I get around 40fps with modpack and at lowest setting . And secondly my 1.20 dont even launches . This error comes in my screen.
![Capture](https://github.com/ItziSpyder/ClickCrystals/assets/127299719/4b4c6ffb-ac3e-4fab-9d7b-09c2f13dbd34)

**Comment by ItzNoOne** [comment]
## update ur driver(lets continue in discord)

**Comment by Ragua7065** [comment]
Its fully up to date. I know this issue is because of my gpu dont support opengl 4.6. It only support opengl 2.1 . I have tried alot of things to make it playable but is unable. I dont think u can help me in that .

**Comment by Ragua7065** [comment]
My dc : saviour4849

**Comment by ItzNoOne** [comment]
### Please join the click crystal discord server and I will talk with u
