### ISSUE TITLE
oi i enable bright orange and it stay

### ISSUE THREAD

**Issue by JelllyFace8** [ItziSpyder/ClickCrystals#9]
Oi I enabled bright orange thing and i turned it off and it stayed! 🤓

**Comment by ItziSpyder** [comment]
> Oi I enabled bright orange thing and i turned it off and it stayed! 🤓

The `BrightOrange` overlay will be removed after you disable the module. Your issue was most likely caused by `TotemOverlay`, which renders a bright red overlay if you have a totem in your inventory but don't have it equipped, and mistakenly thought it was the `BrightOrange` overlay. Try disabling both modules to see if it really was the `BrightOrange` module.

**Comment by JelllyFace8** [comment]
oi ok

**Comment by JelllyFace8** [comment]
oi it worked ily
